old-photo-pipeline: old-photo-pipeline.c image-lib.c image-lib.h threads_images.c threads_images.h
	gcc old-photo-pipeline.c image-lib.c image-lib.h threads_images.c threads_images.h -g -o old-photo-pipeline -lgd -lpthread
