old-photo-paralelo-B: old-photo-paralelo-B.c image-lib.c image-lib.h threads_images.c threads_images.h
	gcc old-photo-paralelo-B.c image-lib.c image-lib.h threads_images.c threads_images.h -g -o old-photo-paralelo-B -lgd -lpthread
