old-photo-paralelo-A: old-photo-paralelo-A.c image-lib.c image-lib.h threads_images.c threads_images.h
	gcc old-photo-paralelo-A.c image-lib.c image-lib.h threads_images.c threads_images.h -g -o old-photo-paralelo-A -lgd -lpthread
